### PR TITLE
Fix GitHub format

### PR DESCRIPTION
**Pull request by LucasMZReal**
here >

### CODE REVIEW

**Comment by Dinnyesensei** [comment]
I don't see any reason why to do that.

**Comment by LucasMZReal** [comment]
@Dinnyesensei because it's broken periodt.

**Comment by LucasMZReal** [comment]
https://www.youtube.com/watch?v=ls8Ta0wq2fE

**Comment by Dinnyesensei** [comment]
How is it broken? It works for me.

**Comment by LucasMZReal** [comment]
> How is it broken? It works for me.

It works I'm talking about the github, the source code should not be the rbxml file, a release should be the rbxml file. The source code should be a lua file.

**Comment by LucasMZReal** [comment]
@xsticcy hey get alive please

**Comment by Dinnyesensei** [comment]
I'm alive but nobody uses this module anyway.

**Comment by LucasMZReal** [comment]
You have two accounts?? I didn't think it was you 😿

**Pull request closed without merging**
